services:
  db:
    image: postgres:16
    container_name: sereia-api-postgres
    restart: always
    environment:
      POSTGRES_USER: sereia
      POSTGRES_PASSWORD: sereia
      POSTGRES_DB: sereia
    ports:
      - "5432:5432"
    volumes:
      - sereia_postgres_data:/var/lib/postgresql/data

volumes:
  sereia_postgres_data:
